// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// neon-config.env is the project-local store for SHADOW_DATABASE_URL
// (and is the source of staging/production DB URLs that npm scripts inject
// into DATABASE_URL). dotenv/config only picks up .env, so load it explicitly.
loadEnv({ path: "neon-config.env", override: false });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
